"""initial

Revision ID: 960e5e3b4593
Revises: 
Create Date: 2016-01-16 16:16:53.287479

"""

# revision identifiers, used by Alembic.
revision = '960e5e3b4593'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('white', sa.String(), nullable=True),
    sa.Column('black', sa.String(), nullable=True),
    sa.Column('epd', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('move_count', sa.Integer(), nullable=True),
    sa.Column('claim_draw', sa.Boolean(), nullable=True),
    sa.Column('turn', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_black'), 'games', ['black'], unique=False)
    op.create_index(op.f('ix_games_white'), 'games', ['white'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_white'), table_name='games')
    op.drop_index(op.f('ix_games_black'), table_name='games')
    op.drop_table('games')
    ### end Alembic commands ###
